name: diary_ai

description: AI 일기장 앱

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.0.1
  geolocator: ^10.0.1
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.7
  http: ^1.1.0
  path_provider: ^2.1.2
  table_calendar: ^3.0.9
  url_launcher: ^6.2.6
  common_utils_services:
    path: D:\develop\flutter_common_utils_service\common_utils_services

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true 